apiVersion: v1
kind: Service
metadata:
  name: fabdns
  namespace: fabedge
spec:
  selector:
    app: fabdns
  type: ClusterIP
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
