apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fab-dns
rules:
  - apiGroups:
      - dns.fabedge.io
    resources:
      - globalservices
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabedge-operator
  namespace: fabedge

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fab-dns:fabedge-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fab-dns
subjects:
  - kind: ServiceAccount
    name: fabedge-operator
    namespace: fabedge