# 当service-hub以server mode运行时需要
apiVersion: v1
kind: Service
metadata:
  name: service-hub-api
spec:
  selector:
    app: service-hub
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
